version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: product
      MYSQL_DATABASE: productservicesst
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "7900:3306"
